const path = require("path");
const { VanillaExtractPlugin } = require("@vanilla-extract/webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  // entry: {
  //   index: path.join(__dirname, "./src/index.ts"),
  //   a: path.join(__dirname, "./src/a/index.tsx"),
  //   b: path.join(__dirname, "./src/b/index.tsx"),
  // },
  entry: "./src/index.ts",
  mode: "production",
  resolve: {
    extensions: [".js", ".json", ".ts", ".tsx"],
  },
  devtool: "source-map",

  plugins: [
    new HtmlWebpackPlugin(),
    new VanillaExtractPlugin(),
    new MiniCssExtractPlugin({
      filename: "index.css",
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(js|ts|tsx)$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: "babel-loader",
            options: {
              babelrc: false,
              presets: [
                "@babel/preset-typescript",
                ["@babel/preset-react", { runtime: "automatic" }],
                [
                  "@babel/preset-env",
                  { targets: { node: 14 }, modules: false },
                ],
              ],
              plugins: ["@vanilla-extract/babel-plugin"],
            },
          },
          "ts-loader",
        ],
      },
      {
        test: /\.css$/i, // Targets only CSS files generated by vanilla-extract
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: require.resolve("css-loader"),
            options: {
              url: false, // Required as image imports should be handled via JS/TS import statements
            },
          },
        ],
      },
    ],
  },

  stats: "minimal",
  output: {
    //   globalObject: "this",
    path: path.resolve(__dirname, "dist"),
    clean: true,
    filename: "index.js",
    //   libraryTarget: "umd",
    //   library: "ts-vanilla-library",
    //   umdNamedDefine: true,
  },
};
